### ISSUE TITLE
Timeouts, failures

### ISSUE THREAD

**Issue by johnkors** [Asana/create-app-attachment-github-action#13]
Maybe set a timeout, and not fail the build if timed out(?). Seeing 8 minutes of our build belonging to Asana is a bit worrysome.

![image](https://user-images.githubusercontent.com/206726/187703233-c9b70270-f64b-4a23-a948-afd24da79bf7.png)

**Comment by mccarron** [comment]
Also seeing this exact same issue with these Actions failing for the past day, and nothing is on their status page: https://status.asana.com/

**Comment by kmeyerhofer** [comment]
![Screenshot from 2022-10-26 14-03-23](https://user-images.githubusercontent.com/24800059/198125942-fa45cf79-a59c-454d-b710-f53ca1c302d0.png)
I had to manually cancel these jobs, which were running for 92+ minutes. Luckily we are using self-hosted runners for these jobs.

**Comment by johnkors** [comment]
Should have been set as a sensible default in this action, but at least github action supports this:
```diff
  uses: Asana/create-app-attachment-github-action@latest
  with:
    asana-secret: ${{ secrets.ASANA_SECRET }}
+ continue-on-error: true
+ timeout-minutes: 1
```

**Comment by kmeyerhofer** [comment]
> Should have been set as a sensible default in this action, but at least github action supports this:
> 
> ```diff
>   uses: Asana/create-app-attachment-github-action@latest
>   with:
>     asana-secret: ${{ secrets.ASANA_SECRET }}
> + continue-on-error: true
> + timeout-minutes: 1
> ```

@johnkors I forgot about this property. Thanks!

**Comment by johnkors** [comment]
Closing, as nobody is listening
