### ISSUE TITLE
Deprecation warnings

### ISSUE THREAD

**Issue by kachkaev** [Asana/create-app-attachment-github-action#16]
Hi folks! 👋

I’m using `Asana/create-app-attachment-github-action@latest` and it produces these two warnings on GitHub UI:

- **create-asana-attachment-job**
  Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: Asana/create-app-attachment-github-action

- **create-asana-attachment-job**
  The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Example job run: https://github.com/hashintel/hash/actions/runs/3312497037

Could you please allocate some time to fix this? 🙏

---
**UPD:** fixable by https://github.com/Asana/create-app-attachment-github-action/pull/15

**Comment by stefafafan** [comment]
The exact same issues for https://github.com/Asana/comment-on-task-github-action as well 🙏🏻 
Pull Requested at https://github.com/Asana/comment-on-task-github-action/pull/9
